changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 Exciting New Features
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🧰 Maintenance & Under the Hood
      labels:
        - chore
        - refactor
        - dependencies
